name: 'Get and cache dependencies'
description: 'Gets and caches node dependencies'

inputs:
  caching:
    description: 'Whether to cache or not'
    required: false
    default: true

outputs:
  used-cache:
    description: 'Whether cache used'
    value: ${{ steps.install.outputs.used-cache }}
runs:
  using: 'composite'
  steps:
      - name: Cache dependencies
        id: cache
        if: inputs.caching == 'true'
        uses: actions/cache@v3
        with:
          path: node_modules
          key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
      - name: Install dependencies
        if: steps.cache.outputs.cache-hit != 'true' || inputs.caching != 'true'
        id: install
        run: | 
          npm ci
          echo "used-cache=true" >> "$GITHUB_OUTPUT"
        shell: bash