name: Reusable Deploy
on: 
    workflow_dispatch:
    workflow_call:
        inputs:
            param1:
                description: first parameter
                required: true
                type: string
            param2:
                description: second parameter
                required: true
                type: string
        secrets:
            myusername:
                description: db username
                required: true
            mypassword:
                description: db password
                required: true
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
            echo "Deploying and uploading Param1 ${{ inputs.param1 }}"
            echo "Deploying and uploading Param2 ${{ inputs.param2 }}"
            echo "Deploying and uploading my username ${{ secrets.myusername }}"
            echo "Deploying and uploading my password ${{ secrets.mypassword }}"