name: Reusable Deploy
on: 
    workflow_dispatch:
    workflow_call:
        inputs:
            param1:
                description: first parameter
                required: true
                type: string
            param2:
                description: second parameter
                required: true
                type: string
        secrets:
            myusername:
                description: db username
                required: true
            mypassword:
                description: db password
                required: true
        outputs:
            deploy-url:
                description: Deploy url
                value: ${{ jobs.deploy.outputs.deploy-url }}
            deploy-token:
                description: Deploy token
                value: ${{ jobs.deploy.outputs.deploy-token }}
jobs:
  deploy:
    runs-on: ubuntu-latest
    outputs: 
        deploy-url: ${{ steps.output-param-url.outputs.deploy-url }}
        deploy-token: ${{ steps.output-param-token.outputs.deploy-token }}
    steps:
      - name: Output information
        run: |
            echo "Deploying and uploading Param1 ${{ inputs.param1 }}"
            echo "Deploying and uploading Param2 ${{ inputs.param2 }}"
            echo "Deploying and uploading my username ${{ secrets.myusername }}"
            echo "Deploying and uploading my password ${{ secrets.mypassword }}"
      - name: Setting URL output param
        id: output-param-url
        run: echo "deploy-url=myapp.mycloud.com" >> "$GITHUB_OUTPUT"
      - name: Setting token output param
        id: output-param-token
        run:  echo "deploy-token=t1t2t3" >> "$GITHUB_OUTPUT"